<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TempleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempleRepository extends EntityRepository
{
}
